---

# This taskset installs basic packages, inserts dotfiles, sets hotkeys and other basic operations

- name: (basics) - Set hostname first before registering things
  hostname:
    name: "{{ custom_hostname | default('feddy') }}"
    use: systemd
  become: true

- name: (basics) - Install basic packages
  dnf:
    name:
      - remmina
      - firefox
      - podman
      - podman-compose
      - flameshot
      - clipman
      - qalculate-gtk
      - openvpn
      - openconnect
      - sshpass
      - python3-pip
      - redshift
      - fzf
    state: present
  become: true

- name: (basics) - Install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - virtualenv
  become: false

# TODO: dotfiles, etc.

- name: (basics) - Ensure neccesary config folders exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - ~/.config/xfce4/terminal
    - ~/.config/Thunar/
  become: false

- name: (basics) - Copy dotfiles over
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - src: basics/vimrc 
      dst: ~/.vimrc
    - src: basics/redshift.conf
      dst: ~/.config/redshift.conf
    - src: basics/bashrc
      dst: ~/.bashrc
    - src: basics/thunar_uca.xml # Thunar file manager custom actions; TODO: check for more
      dst: ~/.config/Thunar/uca.xml
    - src: basics/terminalrc
      dst: ~/.config/xfce4/terminal/terminalrc
  become: false

...