---

# This taskset installs basic packages, inserts dotfiles, sets hotkeys and other basic operations

- name: (basics) - Set hostname first before registering things
  hostname:
    name: "{{ custom_hostname | default('feddy') }}"
    use: systemd
  become: true

- name: (basics) - Install basic packages
  dnf:
    name:
      - remmina # rdp, vnc, etc.
      - firefox
      - evolution
      - podman
      - podman-compose
      - flameshot # snipping tool
      - clipman # Clipboard manager
      - qalculate-gtk # calculate anything
      - openvpn # for openvpn stuff
      - openconnect # for cisco anyconnect (not openvpn compatible)
      - sshpass # to make ansible work
      - python3-pip
      - redshift # save your eyes
      - fzf # fuzzy finder
      - meld # diff gui
      - clapper # video player
    state: present
  become: true

- name: (basics) - Remove default packages
  dnf:
    name:
      - claws-mail # replaced by evolution
      - geany # replaced by vscode
      - galculator # replaced by qalculate
      - gnumeric # replaced by onlyoffice suite
      - parole # replaced by clapper
    state: absent
  become: true

- name: (basics) - Install RPM fusion stuff
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm
    disable_gpg_check: true
    state: present
  become: true

- name: (basics) - Install codecs etc. to make firefox work properly
  dnf:
    name:
      - '@multimedia' # stuff to make firefox work
      - '@sound-and-video'
      - ffmpeg-libs
    state: present
  become: true

- name: (basics) - Install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - virtualenv
  become: false

# TODO: dotfiles, etc.

- name: (basics) - Ensure neccesary config folders exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - ~/.config/xfce4/terminal
    - ~/.config/Thunar/
  become: false

- name: (basics) - Copy dotfiles over
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - src: basics/vimrc 
      dst: ~/.vimrc
    - src: basics/redshift.conf
      dst: ~/.config/redshift.conf
    - src: basics/bashrc
      dst: ~/.bashrc
    - src: basics/thunar_uca.xml # Thunar file manager custom actions; TODO: check for more
      dst: ~/.config/Thunar/uca.xml
    - src: basics/terminalrc
      dst: ~/.config/xfce4/terminal/terminalrc
  become: false

...
