---

# This taskset installs basic packages, inserts dotfiles, sets hotkeys and other basic operations

- name: (basics) - Set hostname first before registering things
  hostname:
    name: "{{ custom_hostname | default('feddy') }}"
    use: systemd
  become: true

- name: (basics) - Install basic dnf packages
  dnf:
    name: "{{ install_basic_packages_dnf }}"
    state: present
  become: true

- name: (basics) - Install RPM fusion stuff
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm # needed for ffmpeg, etc.
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm # needed for dropbox, etc.
    disable_gpg_check: true
    state: present
  become: true

- name: (basics) - Swap out the fedora ffmpeg-free package for the rpmfusion version
  command: dnf swap ffmpeg-free ffmpeg --allowerasing -y
  register: _dnf_results
  changed_when: "'Nothing to do.' not in _dnf_results.stdout_lines"
  when: '"gnome" in feddy_environment' # TODO: Not sure if this is a problem with gnome, or just after Fedora 37 in general. Needs testing on xfce
  become: true

- name: (basics) - Install codecs etc. to make firefox work properly
  dnf:
    name:
      - '@multimedia' # stuff to make firefox work
      #- '@sound-and-video' # No packages in this one, and optional ones conflict with existing packages
      - ffmpeg-libs
    state: present
  become: true

- name: (basics) - Enable third-party repos
  dnf:
    name: fedora-workstation-repositories
    state: present
  become: true

- name: (basics) - Install basic flatpak packages
  community.general.flatpak:
    name: "{{ install_basic_packages_flatpak }}"
    state: present

- name: (basics) - Install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - virtualenv
    - psutil # for gnome / dconf
  become: false

- name: (basics) - Copy dotfiles over
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - src: basics/vimrc 
      dst: ~/.vimrc
    - src: basics/bashrc
      dst: ~/.bashrc
    - src: basics/tmux.conf
      dst: ~/.tmux.conf
  become: false

...
