---

# This taskset installs basic packages, inserts dotfiles, sets hotkeys and other basic operations

- name: (basics) - Set hostname first before registering things
  hostname:
    name: "{{ custom_hostname | default('feddy') }}"
    use: systemd
  become: true

- name: (basics) - Install basic packages
  dnf:
    name: "{{ install_basic_packages }}"
    state: present
  become: true

- name: (basics) - Fetch the fedora version to get the correct RPM fusion link
  command: 'rpm -E %fedora'
  register: version_cmd
  check_mode: no

- name: (basics) - Install RPM fusion stuff
  dnf:
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ version_cmd.stdout }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ version_cmd.stdout }}.noarch.rpm
    disable_gpg_check: true
    state: present
  become: true

- name: (basics) - Install codecs etc. to make firefox work properly
  dnf:
    name:
      - '@multimedia' # stuff to make firefox work
      - '@sound-and-video'
      - ffmpeg-libs
    state: present
  become: true

- name: (basics) - Install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - ansible
    - virtualenv
  become: false

- name: (basics) - Copy dotfiles over
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - src: basics/vimrc 
      dst: ~/.vimrc
    - src: basics/bashrc
      dst: ~/.bashrc
    # TODO: tmux
  become: false

...
