---

# This taskset installs and enables dropbox

#- name: (dropbox) - Fetch and unarchive the dropbox installer
#  unarchive:
#    remote_src: true
#    src: https://www.dropbox.com/download?plat=lnx.x86_64
#    dest: ~/
#    creates: ~/.dropbox-dist/dropboxd # Only when this file doesn't exist
#  become: false

- name: (dropbox) - Install dropbox nautilus extension (requires rpmfusion non-free)
  dnf:
    name: nautilus-dropbox
    state: present
  become: true

- name: (dropbox) - Ensure directory for userspace systemd exists
  file:
    path: ~/.config/systemd/user
    recurse: yes
    state: directory
  become: false

- name: (dropbox) - Copy over the systemd unit file
  copy:
    src: dropbox.service.j2
    dest: ~/.config/systemd/user/dropbox.service
  notify: Daemon_reload
  become: false

- name: (dropbox) - Enable the systemd unit file in userspace (dont start until next reboot though)
  systemd:
    name: dropbox
    scope: user
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}" # Funny business to let you start services in user scope
  become: false

...