---

# Window list at the bottom

- name: (gnome_other) - List the enabled gnome-extensions
  command: gnome-extensions list --enabled
  register: _extensions_list
  changed_when: false
  become: false

- name: (gnome_other) - Enable the window list extension when it isn't already enabled
  command: gnome-extensions enable window-list@gnome-shell-extensions.gcampax.github.com
  when: "'window-list@gnome-shell-extensions.gcampax.github.com' not in _extensions_list.stdout_lines"
  become: false

# Terminal theme stuff

- name: (gnome_other) - Get the terminal profiles list
  dconf:
    state: read
    key: "/org/gnome/terminal/legacy/profiles:/list"
  register: _terminal_profiles
  become: false

- name: (gnome_other) - Create a temporary list to work with
  set_fact:
    _wip_profile_list: "{{ _terminal_profiles.value }}"
  become: false

- name: Compile a list of the profiles, generating a uuid from the profile name
  set_fact:
    _wip_profile_list: "{{  _wip_profile_list + [item.profile_name | to_uuid] }}"
  when: (item.profile_name | to_uuid) not in _wip_profile_list
  loop: "{{ gnome_terminal_settings | dict2items(key_name='profile_name',value_name='profile_values') }}"
  become: false

- name: (gnome_other) - Add the new profiles with dconf
  dconf:
    key: /org/gnome/terminal/legacy/profiles:/list
    value: "{{ _wip_profile_list }}"
  become: false

- name: Initialize transformed settings
  set_fact:
    transformed_gnome_terminal_settings: []
  become: false

- name: Transform settings for each profile
  set_fact:
    transformed_gnome_terminal_settings: >-
      {{
        transformed_gnome_terminal_settings
        + gnome_terminal_settings[item.key]
        | map('combine', {'profile': item.key})
        | list
      }}
  with_dict: "{{ gnome_terminal_settings }}"
  become: false

- name: Debug transformed settings
  debug:
    var: transformed_gnome_terminal_settings
  become: false

- name: (gnome_other) - Loop through each entry, creating stuff as you go
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.profile | to_uuid }}/{{ item.key }}" # pay attention to the colons
    value: "{{ item.val }}"
  loop: "{{ transformed_gnome_terminal_settings }}"
  become: false

- name: (gnome_other) - Set the Solarized dark dircolors, for pretty directory listings
  copy:
    src: gnome_other/dircolors.ansi-dark
    dest: ~/.dircolors
    mode: '0644'
  become: false

# TODO: Add the AppIndicator and KStatusNotifier Support if possible
