---

# Window list at the bottom

- name: (gnome_other) - List the enabled gnome-extensions
  command: gnome-extensions list --enabled
  register: _extensions_list
  changed_when: false
  become: false

- name: (gnome_other) - Enable the window list extension when it isn't already enabled
  command: gnome-extensions enable window-list@gnome-shell-extensions.gcampax.github.com
  when: "'window-list@gnome-shell-extensions.gcampax.github.com' not in _extensions_list.stdout_lines"
  become: false

# Terminal theme stuff

- name: (gnome_other) - Get the terminal profiles list
  dconf:
    state: read
    key: "/org/gnome/terminal/legacy/profiles:/list"
  register: _terminal_profiles
  become: false

- name: (gnome_other) - Create a variable to work with
  set_fact:
    _terminal_profile_custom: ""
  become: false

- name: (gnome_other) - Select a custom profile if it has been defined and exists
  set_fact:
    _terminal_profile_custom: "{{ terminal_profile_to_edit }}"
  when:
    - terminal_profile_to_edit != ""
    - terminal_profile_to_edit in _terminal_profiles.value
  become: false

- name: (gnome_other) - If list is empty, and custom profile is not defined, create a profile
  when:
    - not _terminal_profiles.value or _terminal_profiles.value | length == 0
    - terminal_profile_to_edit == ""
  block:
    - name: (gnome_other) - Create a random uuid
      set_fact:
        _random_uuid: "{{ 9999999999999999999999 | random | to_uuid }}"
    - name: (gnome_other) - Set it as the terminal profile to change
      set_fact:
        _terminal_profile_custom: "{{ _random_uuid }}"
    - name: (gnome_other) - Set it in dconf as a new profile
      dconf:
        key: /org/gnome/terminal/legacy/profiles:/list
        value: "['{{ _random_uuid }}']"
  become: false

- name: (gnome_other) - If list is not empty and custom profile is not defined, select the first profile by default
  vars:
    _intermediary: "{{ _terminal_profiles.value }}"
  set_fact:
    _terminal_profile_custom: "{{ _intermediary[0] }}"
  when:
    - terminal_profile_to_edit == ""
    - _terminal_profile_custom == ""
    - _terminal_profiles.value
  become: false

- name: (gnome_other) - If a terminal profile was decided, set the dracula theme
  when: _terminal_profile_custom != ""
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ _terminal_profile_custom }}/{{ item.key }}" # pay attention to the colons
    value: "{{ item.val }}"
  loop: "{{ gnome_terminal_settings }}"
  become: false

- name: (gnome_other) - Set the Solarized dark dircolors, for pretty directory listings
  copy:
    src: gnome_other/dircolors.ansi-dark
    dest: ~/.dircolors
    mode: '0644'
  become: false

# TODO: Add the AppIndicator and KStatusNotifier Support if possible
