---

# Window list at the bottom

- name: (gnome_other) - List the enabled gnome-extensions
  command: gnome-extensions list --enabled
  register: _extensions_list
  changed_when: false
  become: false

- name: (gnome_other) - Enable the window list extension when it isn't already enabled
  command: gnome-extensions enable window-list@gnome-shell-extensions.gcampax.github.com
  when: "'window-list@gnome-shell-extensions.gcampax.github.com' not in _extensions_list.stdout_lines"
  become: false


# TODO: Add the AppIndicator and KStatusNotifier Support if possible
