---

# This taskset installs and configures keepassxc

- name: (keepassxc) - Install keepassxc
  dnf:
    name: keepassxc
    state: present
  become: true

- name: (keepassxc) - Configure keepassxc
  ini_file:
    path: ~/.config/keepassxc/keepassxc.ini
    no_extra_spaces: true
    section: "{{ item.section }}"
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  loop: "{{ keepass_settings }}"
  become: false
...
