---

- name: (main) - Import basics.yml
  include_tasks: basics.yml
  tags: [basics]

- name: (main) - Import dropbox.yml
  include_tasks: dropbox.yml
  tags: [dropbox]

- name: (main) - Import keepassxc.yml
  include_tasks: keepassxc.yml
  tags: [keepassxc]

- name: (main) - Import libvirt_qemu.yml
  include_tasks: libvirt_qemu.yml
  tags: [kvm]

- name: (main) - Import vscode.yml
  include_tasks: vscode.yml
  tags: [vscode]

- name: (main) - Import onlyoffice.yml
  include_tasks: onlyoffice.yml
  tags: [onlyoffice]

- name: (main) - Import obsidian.yml
  include_tasks: obsidian.yml
  tags: [obsidian]

- name: (main) - Import xfce_whiskermenu.yml
  include_tasks: xfce_whiskermenu.yml
  tags: [xfce]

- name: (main) - Import flameshot_qr.yml
  include_tasks: flameshot_qr.yml
  tags: [qr]

...