---

- name: (main) - Import basics.yml
  import_tasks: basics.yml
  tags: [basics]

- name: (main) - Import xfce_basics.yml
  import_tasks: xfce_basics.yml
  when: '"xfce" in feddy_environment'
  tags: [xfce_basics]

- name: (main) - Import dropbox.yml
  import_tasks: dropbox.yml
  when: configure_dropbox
  tags: [dropbox]

- name: (main) - Import cloud_mount
  import_tasks: cloud_mount.yml
  when: configure_cloud_mount
  tags: [cloud_mount]

- name: (main) - Import keepassxc.yml
  import_tasks: keepassxc.yml
  when: configure_keepassxc
  tags: [keepassxc]

- name: (main) - Import libvirt_qemu.yml
  import_tasks: libvirt_qemu.yml
  when: configure_libvirt_qemu
  tags: [kvm]

- name: (main) - Import vscode.yml
  import_tasks: vscode.yml
  when: configure_vscode
  tags: [vscode]

- name: (main) - Import onlyoffice.yml
  import_tasks: onlyoffice.yml
  when: configure_onlyoffice
  tags: [onlyoffice]

- name: (main) - Import obsidian.yml
  import_tasks: obsidian.yml
  when: configure_obsidian
  tags: [obsidian]

- name: (main) - Import gnome_dconf.yml
  import_tasks: gnome_dconf.yml
  when: '"gnome" in feddy_environment'
  tags: [gnome_dconf]

- name: (main) - Import gnome_other.yml
  import_tasks: gnome_other.yml
  when: '"gnome" in feddy_environment'
  tags: [gnome_dconf]

- name: (main) - Import xfce_whiskermenu.yml
  import_tasks: xfce_whiskermenu.yml
  when:
    - '"xfce" in feddy_environment'
    - configure_xfce_whiskermenu
  tags: [xfce]

- name: (main) - Import flameshot_qr.yml
  import_tasks: flameshot_qr.yml
  when: configure_flameshot_qr
  tags: [qr]

...