---

# This taskset installed obsidian.md and adds the appimage to the applications list

- name: (obsidian) - Download Obsidian AppImage
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.9/Obsidian-1.1.9.AppImage
    dest: /usr/local/bin/obsidian
    mode: '0755'
  become: true

- name: (obsidian) - Check that the dekstop file exists
  stat:
    path: /usr/share/applications/obsidian.desktop
  register: desktop_file
  become: true

- when: not desktop_file.stat.exists
  become: true
  block:

    - name: (obsidian) - Unpack the AppImage into a squashfs-root directory
      shell: obsidian --appimage-extract
      args:
        chdir: /usr/local/bin/

    - name: (obsidian) - Extract icons from AppImage
      copy:
        remote_src: true
        src: /usr/local/bin/squashfs-root/usr/share/icons/
        dest: /usr/share/icons/

    - name: (obsidian) - Extract desktop file from AppImage
      copy:
        remote_src: true
        src: /usr/local/bin/squashfs-root/obsidian.desktop
        dest: /usr/share/applications/

- name: (obsidian) - Remove the squashfs-root directory again
  file:
    path: /usr/local/bin/squashfs-root
    state: absent
  become: true

- name: (obsidian) - Ensure that the Exec field is correct
  ini_file:
    path: /usr/share/applications/obsidian.desktop
    no_extra_spaces: true
    section: Desktop Entry
    option: Exec
    value: /usr/local/bin/obsidian
  become: true

# TODO: Config / settings

- name: (obsidian) - Add shortcut for Obsidian
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Super>n' # Open Obsidian notes
      command: 'obsidian'
    - hotkeys: '<Super><Shift>n' # Open Obsidian notes
      command: 'obsidian'
  become: false

...