---

- name: Download Obsidian AppImage
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.1.9/Obsidian-1.1.9.AppImage
    dest: /usr/local/bin/obsidian
    mode: '0755'

- name: Check that the dekstop file exists
  stat:
    path: /usr/share/applications/obsidian.desktop
  register: desktop_file

- when: not desktop_file.stat.exists
  block:

    - name: Unpack the AppImage into a squashfs-root directory
      shell: obsidian --appimage-extract
      args:
        chdir: /usr/local/bin/

    - name: Extract icons from AppImage
      copy:
        remote_src: true
        src: /usr/local/bin/squashfs-root/usr/share/icons/
        dest: /usr/share/icons/

    - name: Extract desktop file from AppImage
      copy:
        remote_src: true
        src: /usr/local/bin/squashfs-root/obsidian.desktop
        dest: /usr/share/applications/

    - name: Remove the squashfs-root directory again
      file:
        path: /usr/local/bin/squashfs-root
        recurse: true
        state: absent

- name: Ensure that the Exec field is correct
  ini_file:
    path: /usr/share/applications/obsidian.desktop
    no_extra_spaces: true
    section: Desktop Entry
    option: Exec
    value: /usr/local/bin/obsidian

# TODO: Config / settings

- name: Add shortcut for Obsidian
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Super>n' # Open Obsidian notes
      command: 'obsidian'
  become: false
...

