---

# This taskset installs VSCode via a repository

- name: (vscode) - Add Microsoft GPG key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: (vscode) - Add VS Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: (vscode) - Install VS Code
  yum:
    name: code
    state: present
  become: true

- name: (vscode) - Make sure the keyring directory exists, to allow persistent login for vscode
  file:
    path: ~/.local/share/keyrings
    state: directory
  become: false

# Config is fetched automatically from github

...