---

# This taskset installs VSCode via a repository

- name: (vscode) - Install VS Code
  flatpak:
    name: com.visualstudio.code
    method: user
    state: present
  become: true

- name: (vscode) - Make sure the keyring directory exists, to allow persistent login for vscode
  file:
    path: ~/.local/share/keyrings
    state: directory
  become: false

# Config is fetched automatically from github

...
