---

- name: Ensure xfce panel folder exists
  file:
    state: directory
    path: ~/.config/xfce4/panel/profiles/
    recurse: true
  become: false

- name: Copy over the panel profiles
  copy:
    src: "{{ item }}"
    dest: ~/.config/xfce4/panel/profiles/
  loop:
    - laptop_only.tar.bz2
    - widescreen.tar.bz2
  become: false
  register: panel_profiles_copy

- name: Set the laptop panel first time
  shell: xfce4-panel-profiles load ~/.config/xfce4/panel/profiles/laptop_only.tar.bz2
  when: panel_profiles_copy.changed
  become: false

- name: Copy over the script
  copy:
    src: hotplug_monitor.sh
    dest: /usr/local/bin/hotplug_monitor
    mode: '0755'
    owner: root
    group: root

- name: Template out the service
  template:
    src: hotplug_hdmi.service.j2
    dest: /etc/systemd/system/hotplug_hdmi.service
  notify: Daemon_reload

- name: Copy over the udev rule
  copy:
    content: |
      ACTION=="change", KERNEL=="card0", SUBSYSTEM=="drm", RUN+="/usr/bin/systemctl start hotplug_hdmi.service"
    dest: /etc/udev/rules.d/95-monitor-hotplug.rules


# TODO: Set the win key to pop up whiskermenu 
# Might need this: https://forum.manjaro.org/t/popping-up-whisker-menu-with-super-key/117865/4 (Alt-F1)
...