---

# This taskset configures a custom set of panel profiles and a udev rule that switched
# profile when plugging in or out an HDMI cable

- name: (xfce_whiskermenu) - Ensure xfce panel folder exists
  file:
    state: directory
    path: ~/.config/xfce4/panel/profiles/
    recurse: true
  become: false

- name: (xfce_whiskermenu) - Copy over the panel profiles
  copy:
    src: "{{ item }}"
    dest: ~/.config/xfce4/panel/profiles/
  loop:
    - laptop_only.tar.bz2
    - widescreen.tar.bz2
  register: panel_profiles_copy
  become: false

- name: (xfce_whiskermenu) - Set the laptop panel first time
  shell: xfce4-panel-profiles load ~/.config/xfce4/panel/profiles/laptop_only.tar.bz2
  when: panel_profiles_copy.changed
  become: false

- name: (xfce_whiskermenu) - Copy over the script
  copy:
    src: hotplug_monitor.sh
    dest: /usr/local/bin/hotplug_monitor
    mode: '0755'
    owner: root
    group: root
  become: true

- name: (xfce_whiskermenu) - Template out the systemd unit file (no need to enable or start it though)
  template:
    src: hotplug_hdmi.service.j2
    dest: ~/.config/systemd/user/hotplug_hdmi.service
  become: false

- name: (xfce_whiskermenu) - Copy over the udev rule
  copy:
    content: |
      ACTION=="change", KERNEL=="card0", SUBSYSTEM=="drm", RUN+="/usr/bin/systemctl start hotplug_hdmi.service"
    dest: /etc/udev/rules.d/95-monitor-hotplug.rules


# Set the win key to pop up whiskermenu
# Based on stargazer's reply in https://forum.manjaro.org/t/popping-up-whisker-menu-with-super-key/117865/4

- name: (basics) - Add shortcuts for xfce4-popup-whiskermenu to Alt-F1
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Alt>F1'
      command: xfce4-popup-whiskermenu

- name: (xfce_whiskermenu) - Rebind Win key release to Alt-F1
  copy:
    src: xcape.desktop
    dest: ~/.config/autostart/xcape.desktop
    mode: '0664'
  become: false
...