---

- name: (xfce_basics) - Install basic packages
  dnf:
    name:
      - redshift # save your eyes (not working for wayland i think)
      - mpv # video player
    state: present
  become: true

- name: (xfce_basics) - Remove default packages for xfce
  dnf:
    name:
      - claws-mail # replaced by evolution
      - geany # replaced by vscode
      - galculator # replaced by qalculate
      - gnumeric # replaced by onlyoffice suite
      - parole # replaced by mpv
    state: absent
  become: true

- name: (xfce_basics) - Ensure neccesary config folders exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - ~/.config/xfce4/terminal
    - ~/.config/Thunar/
  become: false

- name: (xfce_basics) - Copy dotfiles over
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - src: basics/redshift.conf
      dst: ~/.config/redshift.conf
    - src: basics/thunar_uca.xml
      dst: ~/.config/Thunar/uca.xml
    - src: basics/terminalrc
      dst: ~/.config/xfce4/terminal/terminalrc
  become: false

- name: (xfce_basics) - Add shortcuts for xfce4 (general keyboard stuff)
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Super>Return' # Launch terminal
      command: 'exo-open --launch TerminalEmulator'
    - hotkeys: '<Shift><Super>s' # Open flameshot
      command: 'flameshot gui'
    - hotkeys: '<Super>k' # Open calculator
      command: 'qalculate-gtk'
    - hotkeys: '<Super>l' # Lock screen
      command: 'xflock4'
    - hotkeys: '<Super>w' # Open open browser
      command: 'exo-open --launch WebBrowser'
    - hotkeys: '<Super>m' # Launch mail
      command: 'evolution -c mail'
    - hotkeys: '<Super>f' # Search filesystem
      command: 'catfish --hidden'
    - hotkeys: '<Super>y' # Launch calendar
      command: 'evolution -c calendar'
    - hotkeys: '<Super>v' # Launch clipman history
      command: 'xfce4-clipman-history'
    - hotkeys: '<Super>p' # Display settings (quick)
      command: 'xfce4-display-settings --minimal' # Might need to override this elsewhere
    - hotkeys: '<Shift><Super>p' # Display settings
      command: 'xfce4-display-settings'
    - hotkeys: '<Super><Shift>n' # Open Obsidian notes
      command: 'obsidian'
    - hotkeys: '<Primary><Alt>k' # Open keepass
      command: 'keepassxc'
  become: false

- name: (xfce_basics) - Add shortcuts for xfce4 (window manager stuff)
  xfconf:
    channel: xfwm4
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Super>Left'
      command: 'tile_left_key'
    - hotkeys: '<Super>Right'
      command: 'tile_right_key'
    - hotkeys: '<Super>Down' # Minimize
      command: 'hide_window_key' 
    - hotkeys: '<Super>Up' # Toggle maximize
      command: 'maximize_window_key'
    - hotkeys: '<Super>1' # I never use more than 4 anyway
      command: 'workspace_1_key'
    - hotkeys: '<Super>2'
      command: 'workspace_2_key'
    - hotkeys: '<Super>3'
      command: 'workspace_3_key'
    - hotkeys: '<Super>4'
      command: 'workspace_4_key'
  become: false
  
- name: (xfce_basics) - Set xfce-terminal theme to Dracula
  copy:
    src: Dracula.theme
    dest: ~/.local/share/xfce4/terminal/colorschemes/


- name: (xfce_basics) - Set GTK theme to Adwaita-dark
  xfconf:
    channel: xsettings
    property: "/Net/ThemeName"
    value_type: string
    value: "Adwaita-dark"
  become: false
