---

# This taskset configures a custom set of panel profiles and a udev rule that switched
# profile when plugging in or out an HDMI cable

- name: (xfce_whiskermenu) - Ensure xfce panel folder exists
  file:
    state: directory
    path: ~/.config/xfce4/panel/profiles/
    recurse: true
  become: false

- name: (xfce_whiskermenu) - Copy over the panel profiles
  copy:
    src: "{{ item }}"
    dest: ~/.config/xfce4/panel/profiles/
  loop:
    - xfce_whiskermenu/laptop_only.tar.bz2
    - xfce_whiskermenu/widescreen.tar.bz2
  register: panel_profiles_copy
  become: false

- name: (xfce_whiskermenu) - Set the laptop panel first time
  shell: xfce4-panel-profiles load ~/.config/xfce4/panel/profiles/laptop_only.tar.bz2
  when: panel_profiles_copy.changed
  become: false

- name: (xfce_whiskermenu) - Copy over the script
  copy:
    src: xfce_whiskermenu/hotplug_monitor.sh
    dest: /usr/local/bin/hotplug_monitor
    mode: '0755'
    owner: root
    group: root
  become: true

- name: (xfce_whiskermenu) - Copy over the systemd unit file (no need to enable or start it though)
  copy:
    src: xfce_whiskermenu/hotplug_hdmi.service.j2
    dest: ~/.config/systemd/user/hotplug_hdmi.service
  become: false

- name: (xfce_whiskermenu) - Copy over the udev rule
  copy:
    content: |
      ACTION=="change", KERNEL=="card0", SUBSYSTEM=="drm", RUN+="/usr/bin/systemctl start hotplug_hdmi.service"
    dest: /etc/udev/rules.d/95-monitor-hotplug.rules
  become: true

- name: (xfce_whiskermenu) - Add shortcuts for xfce4-popup-whiskermenu to Win
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.hotkeys }}"
    value_type: string
    value: "{{ item.command }}"
  loop:
    - hotkeys: '<Super_L>'
      command: xfce4-popup-whiskermenu
  become: false


...